name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout@master
        uses: actions/checkout@v1

      - name: deploy to server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
