name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout@master
        uses: actions/checkout@v1

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2

      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-e -c -r --delete --exclude=.git --exclude=.github --exclude=.gitignore"
          SERVER_PORT: ${{ secrets.REMOTE_PORT }}
          FOLDER: "./"
          SERVER_IP: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          SERVER_DESTINATION: ${{ secrets.REMOTE_TARGET }}
