name: Deployment

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: checkout@master
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: ls -als
  deploy:
    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
