name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout@main
        uses: actions/checkout@v1

      - name: build website
        uses: jzweifel/gatsby-cli-github-action@master
        with:
          gatsby-arg: build

      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-e -c -r --delete --exclude=.git --exclude=.github --exclude=.gitignore --exclude=readme.md'
          SERVER_PORT: ${{ secrets.REMOTE_PORT }}
          FOLDER: './public/'
          SERVER_IP: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          SERVER_DESTINATION: ${{ secrets.REMOTE_TARGET }}
