name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Starting deployment
        - run: Deployment is starting
        - name: rsync deployments
        - uses: contention/rsync-deployments@v1.0.0
