name: Deployment

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: checkout@master
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

  deploy:
    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
      - run: ls -als
